spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification_service
    username: myuser
    password: secret
    drive-class-name: com.mysql.cj.jbdc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true 
