services:
  msql:
    container_name: 'db_message_notify'
    image: 'mysql:latest'

    environment:
      - 'MYSQL_DATABASE=db_message_notify'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'

    ports:
      - '3306:3306' 

